"""Constantes compartilhadas por autenticacao, autorizacao e auditoria futuras."""

PERMISSION_OFFERS_READ = "offers:read"
PERMISSION_OFFERS_REVIEW = "offers:review"
PERMISSION_OFFERS_EDIT = "offers:edit"
PERMISSION_OFFERS_PUBLISH = "offers:publish"
PERMISSION_CATALOG_READ = "catalog:read"
PERMISSION_CATALOG_GENERATE = "catalog:generate"
PERMISSION_TELEGRAM_PUBLISH = "telegram:publish"
PERMISSION_SITE_DEPLOY = "site:deploy"
PERMISSION_WORKERS_READ = "workers:read"
PERMISSION_WORKERS_RUN = "workers:run"
PERMISSION_WORKERS_STOP = "workers:stop"
PERMISSION_ANALYTICS_READ = "analytics:read"
PERMISSION_AUDIT_READ = "audit:read"
PERMISSION_USERS_READ = "users:read"
PERMISSION_USERS_MANAGE = "users:manage"
PERMISSION_ROLES_MANAGE = "roles:manage"
PERMISSION_SECRETS_MANAGE = "secrets:manage"
PERMISSION_BACKUP_CREATE = "backup:create"
PERMISSION_BACKUP_RESTORE = "backup:restore"
PERMISSION_SYSTEM_ADMIN = "system:admin"

PERMISSIONS = (
    PERMISSION_OFFERS_READ,
    PERMISSION_OFFERS_REVIEW,
    PERMISSION_OFFERS_EDIT,
    PERMISSION_OFFERS_PUBLISH,
    PERMISSION_CATALOG_READ,
    PERMISSION_CATALOG_GENERATE,
    PERMISSION_TELEGRAM_PUBLISH,
    PERMISSION_SITE_DEPLOY,
    PERMISSION_WORKERS_READ,
    PERMISSION_WORKERS_RUN,
    PERMISSION_WORKERS_STOP,
    PERMISSION_ANALYTICS_READ,
    PERMISSION_AUDIT_READ,
    PERMISSION_USERS_READ,
    PERMISSION_USERS_MANAGE,
    PERMISSION_ROLES_MANAGE,
    PERMISSION_SECRETS_MANAGE,
    PERMISSION_BACKUP_CREATE,
    PERMISSION_BACKUP_RESTORE,
    PERMISSION_SYSTEM_ADMIN,
)

ROLE_ADMIN = "Administrador"
ROLE_OPERATOR = "Operador"
ROLE_REVIEWER = "Revisor"
ROLE_ANALYST = "Analista"
ROLE_READ_ONLY = "Somente leitura"

ROLES = (
    ROLE_ADMIN,
    ROLE_OPERATOR,
    ROLE_REVIEWER,
    ROLE_ANALYST,
    ROLE_READ_ONLY,
)

ERROR_AUTH_DISABLED = "AUTH_DISABLED"
ERROR_AUTH_EXPERIMENTAL_DISABLED = "AUTH_EXPERIMENTAL_DISABLED"
ERROR_INVALID_CREDENTIALS = "INVALID_CREDENTIALS"
ERROR_INVALID_TOKEN = "INVALID_TOKEN"
ERROR_TOKEN_EXPIRED = "TOKEN_EXPIRED"
ERROR_MFA_REQUIRED = "MFA_REQUIRED"
ERROR_PERMISSION_DENIED = "PERMISSION_DENIED"
ERROR_ACCOUNT_LOCKED = "ACCOUNT_LOCKED"
ERROR_RATE_LIMITED = "RATE_LIMITED"
ERROR_VALIDATION = "VALIDATION_ERROR"

ERROR_CODES = (
    ERROR_AUTH_DISABLED,
    ERROR_AUTH_EXPERIMENTAL_DISABLED,
    ERROR_INVALID_CREDENTIALS,
    ERROR_INVALID_TOKEN,
    ERROR_TOKEN_EXPIRED,
    ERROR_MFA_REQUIRED,
    ERROR_PERMISSION_DENIED,
    ERROR_ACCOUNT_LOCKED,
    ERROR_RATE_LIMITED,
    ERROR_VALIDATION,
)

AUDIT_AUTH_LOGIN_SUCCESS = "auth.login.success"
AUDIT_AUTH_LOGIN_FAILURE = "auth.login.failure"
AUDIT_AUTH_LOGOUT = "auth.logout"
AUDIT_AUTH_REFRESH_USED = "auth.refresh.used"
AUDIT_AUTH_REFRESH_REUSED = "auth.refresh.reused"
AUDIT_AUTH_PASSWORD_CHANGED = "auth.password.changed"
AUDIT_AUTH_MFA_ENABLED = "auth.mfa.enabled"
AUDIT_AUTH_MFA_DISABLED = "auth.mfa.disabled"
AUDIT_RBAC_ROLE_CHANGED = "rbac.role.changed"
AUDIT_OFFER_REVIEWED = "offers.reviewed"
AUDIT_OFFER_EDITED = "offers.edited"
AUDIT_TELEGRAM_PUBLISHED = "telegram.published"
AUDIT_SITE_DEPLOYED = "site.deployed"
AUDIT_PRODUCTION_STARTED = "production.started"
AUDIT_PRODUCTION_STOPPED = "production.stopped"
AUDIT_BACKUP_RESTORED = "backup.restored"
AUDIT_SECRETS_CHANGED = "secrets.changed"
AUDIT_LOGS_ACCESSED = "logs.accessed"
AUDIT_DATA_EXPORTED = "data.exported"

AUDIT_EVENTS = (
    AUDIT_AUTH_LOGIN_SUCCESS,
    AUDIT_AUTH_LOGIN_FAILURE,
    AUDIT_AUTH_LOGOUT,
    AUDIT_AUTH_REFRESH_USED,
    AUDIT_AUTH_REFRESH_REUSED,
    AUDIT_AUTH_PASSWORD_CHANGED,
    AUDIT_AUTH_MFA_ENABLED,
    AUDIT_AUTH_MFA_DISABLED,
    AUDIT_RBAC_ROLE_CHANGED,
    AUDIT_OFFER_REVIEWED,
    AUDIT_OFFER_EDITED,
    AUDIT_TELEGRAM_PUBLISHED,
    AUDIT_SITE_DEPLOYED,
    AUDIT_PRODUCTION_STARTED,
    AUDIT_PRODUCTION_STOPPED,
    AUDIT_BACKUP_RESTORED,
    AUDIT_SECRETS_CHANGED,
    AUDIT_LOGS_ACCESSED,
    AUDIT_DATA_EXPORTED,
)

HEADER_AUTHORIZATION = "Authorization"
HEADER_REQUEST_ID = "X-Request-ID"
HEADER_CONTENT_TYPE = "Content-Type"
HEADER_X_CONTENT_TYPE_OPTIONS = "X-Content-Type-Options"
HEADER_REFERRER_POLICY = "Referrer-Policy"
HEADER_X_FRAME_OPTIONS = "X-Frame-Options"
HEADER_PERMISSIONS_POLICY = "Permissions-Policy"
HEADER_CACHE_CONTROL = "Cache-Control"

HTTP_HEADERS = (
    HEADER_AUTHORIZATION,
    HEADER_REQUEST_ID,
    HEADER_CONTENT_TYPE,
    HEADER_X_CONTENT_TYPE_OPTIONS,
    HEADER_REFERRER_POLICY,
    HEADER_X_FRAME_OPTIONS,
    HEADER_PERMISSIONS_POLICY,
    HEADER_CACHE_CONTROL,
)

COOKIE_REFRESH_TOKEN = "promogg_refresh_token"
COOKIE_CSRF_TOKEN = "promogg_csrf_token"
COOKIE_SESSION_HINT = "promogg_session_hint"

COOKIE_NAMES = (
    COOKIE_REFRESH_TOKEN,
    COOKIE_CSRF_TOKEN,
    COOKIE_SESSION_HINT,
)

ENV_AUTH_ENABLED = "PROMOGG_AUTH_ENABLED"
ENV_AUTH_EXPERIMENTAL_ENABLED = "PROMOGG_AUTH_EXPERIMENTAL_ENABLED"
ENV_PROMOGG_ENV = "PROMOGG_ENV"
ENV_MFA_ENABLED = "PROMOGG_MFA_ENABLED"
ENV_JWT_ENABLED = "PROMOGG_JWT_ENABLED"
ENV_JWT_ISSUER = "PROMOGG_JWT_ISSUER"
ENV_JWT_AUDIENCE = "PROMOGG_JWT_AUDIENCE"
ENV_JWT_SIGNING_KEY = "PROMOGG_JWT_SIGNING_KEY"
ENV_JWT_ACCESS_TTL = "PROMOGG_JWT_ACCESS_TTL"
ENV_JWT_REFRESH_TTL = "PROMOGG_JWT_REFRESH_TTL"
ENV_JWT_ALGORITHM = "PROMOGG_JWT_ALGORITHM"
ENV_RBAC_ENABLED = "PROMOGG_RBAC_ENABLED"
ENV_AUDIT_ENABLED = "PROMOGG_AUDIT_ENABLED"
ENV_CSRF_ENABLED = "PROMOGG_CSRF_ENABLED"
ENV_CSRF_COOKIE_NAME = "PROMOGG_CSRF_COOKIE_NAME"
ENV_CSRF_HEADER_NAME = "PROMOGG_CSRF_HEADER_NAME"
ENV_CSRF_TOKEN_TTL = "PROMOGG_CSRF_TOKEN_TTL"
ENV_SESSION_ROTATION_ENABLED = "PROMOGG_SESSION_ROTATION_ENABLED"
ENV_SESSION_IDLE_TIMEOUT = "PROMOGG_SESSION_IDLE_TIMEOUT"
ENV_SESSION_ABSOLUTE_TIMEOUT = "PROMOGG_SESSION_ABSOLUTE_TIMEOUT"
ENV_MAX_LOGIN_ATTEMPTS = "PROMOGG_MAX_LOGIN_ATTEMPTS"
ENV_LOCKOUT_MINUTES = "PROMOGG_LOCKOUT_MINUTES"
ENV_ACCESS_TOKEN_TTL = "PROMOGG_ACCESS_TOKEN_TTL"
ENV_REFRESH_TOKEN_TTL = "PROMOGG_REFRESH_TOKEN_TTL"
ENV_PASSWORD_MIN_LENGTH = "PROMOGG_PASSWORD_MIN_LENGTH"
ENV_PASSWORD_REQUIRE_COMPLEXITY = "PROMOGG_PASSWORD_REQUIRE_COMPLEXITY"
ENV_CORS_ALLOWED_ORIGINS = "PROMOGG_CORS_ALLOWED_ORIGINS"
ENV_ALLOWED_HOSTS = "PROMOGG_ALLOWED_HOSTS"

ENV_VARS = (
    ENV_AUTH_ENABLED,
    ENV_AUTH_EXPERIMENTAL_ENABLED,
    ENV_PROMOGG_ENV,
    ENV_MFA_ENABLED,
    ENV_JWT_ENABLED,
    ENV_JWT_ISSUER,
    ENV_JWT_AUDIENCE,
    ENV_JWT_SIGNING_KEY,
    ENV_JWT_ACCESS_TTL,
    ENV_JWT_REFRESH_TTL,
    ENV_JWT_ALGORITHM,
    ENV_RBAC_ENABLED,
    ENV_AUDIT_ENABLED,
    ENV_CSRF_ENABLED,
    ENV_CSRF_COOKIE_NAME,
    ENV_CSRF_HEADER_NAME,
    ENV_CSRF_TOKEN_TTL,
    ENV_SESSION_ROTATION_ENABLED,
    ENV_SESSION_IDLE_TIMEOUT,
    ENV_SESSION_ABSOLUTE_TIMEOUT,
    ENV_MAX_LOGIN_ATTEMPTS,
    ENV_LOCKOUT_MINUTES,
    ENV_ACCESS_TOKEN_TTL,
    ENV_REFRESH_TOKEN_TTL,
    ENV_PASSWORD_MIN_LENGTH,
    ENV_PASSWORD_REQUIRE_COMPLEXITY,
    ENV_CORS_ALLOWED_ORIGINS,
    ENV_ALLOWED_HOSTS,
)

ENVIRONMENT_DEVELOPMENT = "development"
ENVIRONMENT_STAGING = "staging"
ENVIRONMENT_PRODUCTION = "production"

ENVIRONMENTS = (
    ENVIRONMENT_DEVELOPMENT,
    ENVIRONMENT_STAGING,
    ENVIRONMENT_PRODUCTION,
)

JWT_ALGORITHM_HS256 = "HS256"
JWT_ALLOWED_ALGORITHMS = (JWT_ALGORITHM_HS256,)
JWT_TOKEN_VERSION = "v1"
